### ISSUE TITLE
关于禁用独显的问题

### ISSUE THREAD

**Issue by Kayro11** [Halo-Michael/OC-GA-B250M-EVO-Hackintosh#1]
大佬你好，首先感谢无私分享这么好的EFI以及BIOS文件。
请问这个EFI是怎么禁用的独立显卡的？
我的电脑有个LEXAR核心的RX550X，我想通过注入ID仿冒独立显卡，首先需要知道怎么开启独立显卡。

**Comment by Halo-Michael** [comment]
DeviceProperties->add->PciRoot(0x0)/Pci(0x2,0x0),去掉里面的disable-external-gpu

**Comment by Kayro11** [comment]
感谢大佬，我怎么都搞不定休眠唤醒，搜索了整个网上也没有人搞定过。我的CPU是i5-7500，用的是原版bios，请问有没有对应的EFI文件🙏

**Comment by Halo-Michael** [comment]
> 感谢大佬，我怎么都搞不定休眠唤醒，搜索了整个网上也没有人搞定过。我的CPU是i5-7500，用的是原版bios，请问有没有对应的EFI文件🙏

用这个EFI应该可以直接使用休眠功能

**Comment by Halo-Michael** [comment]
你可以看看你的CFG lock和CSM是不是都禁用了

**Comment by Kayro11** [comment]
> 你可以看看你的CFG lock和CSM是不是都禁用了

我都禁用了，现在被我捣鼓的连引导都进不去了。感谢大佬，我去换个主板，这个主板除了大佬分享的EFI外没有任何EFI被分享过😭

**Comment by Halo-Michael** [comment]
> > 你可以看看你的CFG lock和CSM是不是都禁用了
> 
> 我都禁用了，现在被我捣鼓的连引导都进不去了。感谢大佬，我去换个主板，这个主板除了大佬分享的EFI外没有任何EFI被分享过😭

不至于吧 大不了淘宝买个十块钱的编程器刷一下BIOS重新来过
